view:
  site:
    websiteName: ccblog
    contactMeTitle: 联系我 - czc
    websiteRecord:  备案号:无备案号
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到CC-blog ~~

server-ip: localhost

aggregate:    # 聚合配置
  max-version: 999999 # 版本重置阈值(不过好像没写到类里面,敬请期待)
  none:    # 默认全局值(暂未使用)
    max-count: 30
    redis-log: false
    mq-log: false
  user:
    max-count: 1
    redis-log: false
    mq-log: false
  article:
    max-count: 1
    redis-log: false
    mq-log: false
  comment:
    max-count: 1
    redis-log: false
    mq-log: false
  notice:
    max-count: 1
    redis-log: false
    mq-log: false
  chat:
    max-count: 1
    redis-log: false
    mq-log: false

ai:
  # 讯飞AI
  xunfei:
    qwen:
      baseUrl:
      apiKey:
      secretKey:
    deepseek: # 敬请期待...
      baseUrl:
      apiKey:
      secretKey:

spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 1839156312@qq.com
    password: kkrqahlohbhtbdch # 16位授权码
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true